// Generated by gencpp from file joh_gap_finding/gap.msg
// DO NOT EDIT!


#ifndef JOH_GAP_FINDING_MESSAGE_GAP_H
#define JOH_GAP_FINDING_MESSAGE_GAP_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace joh_gap_finding
{
template <class ContainerAllocator>
struct gap_
{
  typedef gap_<ContainerAllocator> Type;

  gap_()
    : num(0)  {
    }
  gap_(const ContainerAllocator& _alloc)
    : num(0)  {
  (void)_alloc;
    }



   typedef int64_t _num_type;
  _num_type num;





  typedef boost::shared_ptr< ::joh_gap_finding::gap_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::joh_gap_finding::gap_<ContainerAllocator> const> ConstPtr;

}; // struct gap_

typedef ::joh_gap_finding::gap_<std::allocator<void> > gap;

typedef boost::shared_ptr< ::joh_gap_finding::gap > gapPtr;
typedef boost::shared_ptr< ::joh_gap_finding::gap const> gapConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::joh_gap_finding::gap_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::joh_gap_finding::gap_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::joh_gap_finding::gap_<ContainerAllocator1> & lhs, const ::joh_gap_finding::gap_<ContainerAllocator2> & rhs)
{
  return lhs.num == rhs.num;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::joh_gap_finding::gap_<ContainerAllocator1> & lhs, const ::joh_gap_finding::gap_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace joh_gap_finding

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::joh_gap_finding::gap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::joh_gap_finding::gap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joh_gap_finding::gap_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::joh_gap_finding::gap_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joh_gap_finding::gap_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::joh_gap_finding::gap_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::joh_gap_finding::gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "57d3c40ec3ac3754af76a83e6e73127a";
  }

  static const char* value(const ::joh_gap_finding::gap_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x57d3c40ec3ac3754ULL;
  static const uint64_t static_value2 = 0xaf76a83e6e73127aULL;
};

template<class ContainerAllocator>
struct DataType< ::joh_gap_finding::gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "joh_gap_finding/gap";
  }

  static const char* value(const ::joh_gap_finding::gap_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::joh_gap_finding::gap_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int64 num\n"
;
  }

  static const char* value(const ::joh_gap_finding::gap_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::joh_gap_finding::gap_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.num);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct gap_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::joh_gap_finding::gap_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::joh_gap_finding::gap_<ContainerAllocator>& v)
  {
    s << indent << "num: ";
    Printer<int64_t>::stream(s, indent + "  ", v.num);
  }
};

} // namespace message_operations
} // namespace ros

#endif // JOH_GAP_FINDING_MESSAGE_GAP_H
